import { BookOpen, GraduationCap, Stethoscope } from "lucide-react";

// JEE Advanced Data
export const jeeAdvancedTrends = [
  { year: "2019", general: 25000, obc: 18000, sc: 8000, st: 4000 },
  { year: "2020", general: 23000, obc: 16500, sc: 7500, st: 3800 },
  { year: "2021", general: 24500, obc: 17200, sc: 7800, st: 4100 },
  { year: "2022", general: 22000, obc: 15800, sc: 7200, st: 3600 },
  { year: "2023", general: 21500, obc: 15500, sc: 7000, st: 3500 },
];

// JEE Main Data
export const jeeMainTrends = [
  { year: "2019", general: 89.75, obc: 74.31, sc: 54.01, st: 44.33 },
  { year: "2020", general: 90.37, obc: 72.88, sc: 50.17, st: 39.06 },
  { year: "2021", general: 87.89, obc: 68.02, sc: 46.88, st: 34.67 },
  { year: "2022", general: 88.4, obc: 70.29, sc: 48.84, st: 38.96 },
  { year: "2023", general: 89.75, obc: 73.09, sc: 52.49, st: 42.27 },
];

// NEET Data
export const neetTrends = [
  { year: "2019", general: 720, obc: 690, sc: 590, st: 570 },
  { year: "2020", general: 720, obc: 685, sc: 575, st: 555 },
  { year: "2021", general: 720, obc: 687, sc: 586, st: 570 },
  { year: "2022", general: 715, obc: 680, sc: 570, st: 550 },
  { year: "2023", general: 715, obc: 675, sc: 565, st: 545 },
];

export const examData = {
  "JEE-Advanced": {
    name: "JEE Advanced",
    icon: GraduationCap,
    description: "All India Rank based cutoffs for IIT admissions",
    trendData: jeeAdvancedTrends,
    yAxisLabel: "Rank",
    formatValue: (value: number) => `${value}`,
    currentYear: {
      general: 21500,
      obc: 15500,
      sc: 7000,
      st: 3500,
      change: { general: -2.3, obc: -1.9, sc: -2.8, st: -2.9 },
    },
  },
  "JEE-Main": {
    name: "JEE Main",
    icon: BookOpen,
    description: "Percentile based cutoffs for NIT, IIIT admissions",
    trendData: jeeMainTrends,
    yAxisLabel: "Percentile",
    formatValue: (value: number) => `${value}%`,
    currentYear: {
      general: 89.75,
      obc: 73.09,
      sc: 52.49,
      st: 42.27,
      change: { general: 1.5, obc: 4.0, sc: 7.5, st: 8.5 },
    },
  },
  NEET: {
    name: "NEET",
    icon: Stethoscope,
    description: "Score based cutoffs for medical college admissions",
    trendData: neetTrends,
    yAxisLabel: "Score",
    formatValue: (value: number) => `${value}`,
    currentYear: {
      general: 715,
      obc: 675,
      sc: 565,
      st: 545,
      change: { general: 0, obc: -0.7, sc: -0.9, st: -0.9 },
    },
  },
};

export const jeeAdvancedColleges = [
  {
    college: "IIT Bombay",
    cse: 100,
    ee: 600,
    me: 900,
    ce: 1800,
    ranking: "#1",
  },
  {
    college: "IIT Delhi",
    cse: 150,
    ee: 800,
    me: 1200,
    ce: 2000,
    ranking: "#2",
  },
  {
    college: "IIT Kanpur",
    cse: 350,
    ee: 1200,
    me: 1800,
    ce: 2800,
    ranking: "#4",
  },
  {
    college: "IIT Kharagpur",
    cse: 500,
    ee: 1500,
    me: 2200,
    ce: 3200,
    ranking: "#5",
  },
  {
    college: "IIT Roorkee",
    cse: 800,
    ee: 2000,
    me: 3000,
    ce: 4500,
    ranking: "#8",
  },
];

export const jeeMainColleges = [
  {
    college: "NIT Trichy",
    cse: 99.5,
    ee: 98.2,
    me: 97.8,
    ce: 95.4,
    ranking: "#1",
  },
  {
    college: "NIT Surathkal",
    cse: 99.2,
    ee: 97.9,
    me: 97.2,
    ce: 94.8,
    ranking: "#2",
  },
  {
    college: "NIT Warangal",
    cse: 98.8,
    ee: 97.1,
    me: 96.5,
    ce: 94.0,
    ranking: "#3",
  },
  {
    college: "IIIT Hyderabad",
    cse: 99.8,
    ee: null,
    me: null,
    ce: null,
    ranking: "#4",
  },
  {
    college: "NIT Calicut",
    cse: 98.5,
    ee: 96.8,
    me: 96.0,
    ce: 93.5,
    ranking: "#5",
  },
];

export const neetColleges = [
  { college: "AIIMS Delhi", mbbs: 715, bds: null, ranking: "#1" },
  { college: "AIIMS Mumbai", mbbs: 710, bds: null, ranking: "#2" },
  { college: "CMC Vellore", mbbs: 695, bds: null, ranking: "#3" },
  { college: "JIPMER Puducherry", mbbs: 690, bds: null, ranking: "#4" },
  { college: "KMC Manipal", mbbs: 650, bds: 580, ranking: "#5" },
];

// Extended college data for search functionality
export const extendedCollegeData = {
  "jee-advanced": [
    {
      id: 1,
      name: "IIT Bombay",
      location: "Mumbai, Maharashtra",
      ranking: "#1",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 100,
          obc: 85,
          sc: 45,
          st: 25,
          seats: 120,
        },
        {
          name: "Electrical Engineering",
          general: 600,
          obc: 480,
          sc: 220,
          st: 110,
          seats: 100,
        },
        {
          name: "Mechanical Engineering",
          general: 900,
          obc: 720,
          sc: 350,
          st: 180,
          seats: 110,
        },
        {
          name: "Civil Engineering",
          general: 1800,
          obc: 1400,
          sc: 650,
          st: 320,
          seats: 90,
        },
        {
          name: "Chemical Engineering",
          general: 1200,
          obc: 950,
          sc: 450,
          st: 230,
          seats: 80,
        },
      ],
    },
    {
      id: 2,
      name: "IIT Delhi",
      location: "New Delhi, Delhi",
      ranking: "#2",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 150,
          obc: 120,
          sc: 65,
          st: 35,
          seats: 120,
        },
        {
          name: "Electrical Engineering",
          general: 800,
          obc: 640,
          sc: 320,
          st: 160,
          seats: 100,
        },
        {
          name: "Mechanical Engineering",
          general: 1200,
          obc: 960,
          sc: 480,
          st: 240,
          seats: 110,
        },
        {
          name: "Civil Engineering",
          general: 2000,
          obc: 1600,
          sc: 800,
          st: 400,
          seats: 90,
        },
        {
          name: "Chemical Engineering",
          general: 1500,
          obc: 1200,
          sc: 600,
          st: 300,
          seats: 80,
        },
      ],
    },
    {
      id: 3,
      name: "IIT Kanpur",
      location: "Kanpur, Uttar Pradesh",
      ranking: "#4",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 350,
          obc: 280,
          sc: 140,
          st: 70,
          seats: 100,
        },
        {
          name: "Electrical Engineering",
          general: 1200,
          obc: 960,
          sc: 480,
          st: 240,
          seats: 90,
        },
        {
          name: "Mechanical Engineering",
          general: 1800,
          obc: 1440,
          sc: 720,
          st: 360,
          seats: 100,
        },
        {
          name: "Civil Engineering",
          general: 2800,
          obc: 2240,
          sc: 1120,
          st: 560,
          seats: 80,
        },
        {
          name: "Chemical Engineering",
          general: 2200,
          obc: 1760,
          sc: 880,
          st: 440,
          seats: 70,
        },
      ],
    },
    {
      id: 4,
      name: "IIT Kharagpur",
      location: "Kharagpur, West Bengal",
      ranking: "#5",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 500,
          obc: 400,
          sc: 200,
          st: 100,
          seats: 110,
        },
        {
          name: "Electrical Engineering",
          general: 1500,
          obc: 1200,
          sc: 600,
          st: 300,
          seats: 95,
        },
        {
          name: "Mechanical Engineering",
          general: 2200,
          obc: 1760,
          sc: 880,
          st: 440,
          seats: 105,
        },
        {
          name: "Civil Engineering",
          general: 3200,
          obc: 2560,
          sc: 1280,
          st: 640,
          seats: 85,
        },
        {
          name: "Metallurgical Engineering",
          general: 2800,
          obc: 2240,
          sc: 1120,
          st: 560,
          seats: 60,
        },
      ],
    },
    {
      id: 5,
      name: "IIT Roorkee",
      location: "Roorkee, Uttarakhand",
      ranking: "#8",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 800,
          obc: 640,
          sc: 320,
          st: 160,
          seats: 90,
        },
        {
          name: "Electrical Engineering",
          general: 2000,
          obc: 1600,
          sc: 800,
          st: 400,
          seats: 85,
        },
        {
          name: "Mechanical Engineering",
          general: 3000,
          obc: 2400,
          sc: 1200,
          st: 600,
          seats: 95,
        },
        {
          name: "Civil Engineering",
          general: 4500,
          obc: 3600,
          sc: 1800,
          st: 900,
          seats: 80,
        },
        {
          name: "Chemical Engineering",
          general: 3500,
          obc: 2800,
          sc: 1400,
          st: 700,
          seats: 70,
        },
      ],
    },
  ],
  "jee-main": [
    {
      id: 1,
      name: "NIT Trichy",
      location: "Tiruchirappalli, Tamil Nadu",
      ranking: "#1",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 99.5,
          obc: 98.2,
          sc: 89.5,
          st: 82.3,
          seats: 120,
        },
        {
          name: "Electrical Engineering",
          general: 98.2,
          obc: 96.8,
          sc: 85.2,
          st: 78.9,
          seats: 100,
        },
        {
          name: "Mechanical Engineering",
          general: 97.8,
          obc: 96.2,
          sc: 83.5,
          st: 76.2,
          seats: 110,
        },
        {
          name: "Civil Engineering",
          general: 95.4,
          obc: 93.8,
          sc: 79.2,
          st: 72.5,
          seats: 90,
        },
        {
          name: "Electronics & Communication",
          general: 98.8,
          obc: 97.5,
          sc: 87.8,
          st: 80.5,
          seats: 100,
        },
      ],
    },
    {
      id: 2,
      name: "NIT Surathkal",
      location: "Mangalore, Karnataka",
      ranking: "#2",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 99.2,
          obc: 97.8,
          sc: 88.5,
          st: 81.2,
          seats: 110,
        },
        {
          name: "Electrical Engineering",
          general: 97.9,
          obc: 96.2,
          sc: 84.8,
          st: 77.5,
          seats: 95,
        },
        {
          name: "Mechanical Engineering",
          general: 97.2,
          obc: 95.5,
          sc: 82.8,
          st: 75.2,
          seats: 105,
        },
        {
          name: "Civil Engineering",
          general: 94.8,
          obc: 93.2,
          sc: 78.5,
          st: 71.8,
          seats: 85,
        },
        {
          name: "Information Technology",
          general: 98.5,
          obc: 97.1,
          sc: 86.8,
          st: 79.5,
          seats: 80,
        },
      ],
    },
    {
      id: 3,
      name: "NIT Warangal",
      location: "Warangal, Telangana",
      ranking: "#3",
      branches: [
        {
          name: "Computer Science Engineering",
          general: 98.8,
          obc: 97.2,
          sc: 87.5,
          st: 80.2,
          seats: 115,
        },
        {
          name: "Electrical Engineering",
          general: 97.1,
          obc: 95.5,
          sc: 83.2,
          st: 76.5,
          seats: 100,
        },
        {
          name: "Mechanical Engineering",
          general: 96.5,
          obc: 94.8,
          sc: 81.5,
          st: 74.2,
          seats: 110,
        },
        {
          name: "Civil Engineering",
          general: 94.0,
          obc: 92.5,
          sc: 77.8,
          st: 70.5,
          seats: 90,
        },
        {
          name: "Electronics & Communication",
          general: 97.8,
          obc: 96.5,
          sc: 85.8,
          st: 78.5,
          seats: 95,
        },
      ],
    },
  ],
  neet: [
    {
      id: 1,
      name: "AIIMS Delhi",
      location: "New Delhi, Delhi",
      ranking: "#1",
      branches: [
        { name: "MBBS", general: 715, obc: 705, sc: 680, st: 665, seats: 125 },
        { name: "BDS", general: null, obc: null, sc: null, st: null, seats: 0 },
      ],
    },
    {
      id: 2,
      name: "AIIMS Mumbai",
      location: "Mumbai, Maharashtra",
      ranking: "#2",
      branches: [
        { name: "MBBS", general: 710, obc: 700, sc: 675, st: 660, seats: 100 },
      ],
    },
    {
      id: 3,
      name: "CMC Vellore",
      location: "Vellore, Tamil Nadu",
      ranking: "#3",
      branches: [
        { name: "MBBS", general: 695, obc: 685, sc: 650, st: 635, seats: 100 },
        { name: "BDS", general: 650, obc: 640, sc: 610, st: 595, seats: 50 },
      ],
    },
    {
      id: 4,
      name: "JIPMER Puducherry",
      location: "Puducherry",
      ranking: "#4",
      branches: [
        { name: "MBBS", general: 690, obc: 680, sc: 645, st: 630, seats: 200 },
      ],
    },
    {
      id: 5,
      name: "KMC Manipal",
      location: "Manipal, Karnataka",
      ranking: "#5",
      branches: [
        { name: "MBBS", general: 650, obc: 640, sc: 605, st: 590, seats: 150 },
        { name: "BDS", general: 580, obc: 570, sc: 540, st: 525, seats: 80 },
      ],
    },
  ],
};
